// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddResourceOKCode is the HTTP code returned for type AddResourceOK
const AddResourceOKCode int = 200

/*AddResourceOK returns the list of created resources

swagger:response addResourceOK
*/
type AddResourceOK struct {

	/*
	  In: Body
	*/
	Payload *AddResourceOKBody `json:"body,omitempty"`
}

// NewAddResourceOK creates AddResourceOK with default headers values
func NewAddResourceOK() *AddResourceOK {

	return &AddResourceOK{}
}

// WithPayload adds the payload to the add resource o k response
func (o *AddResourceOK) WithPayload(payload *AddResourceOKBody) *AddResourceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add resource o k response
func (o *AddResourceOK) SetPayload(payload *AddResourceOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddResourceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddResourceUnauthorizedCode is the HTTP code returned for type AddResourceUnauthorized
const AddResourceUnauthorizedCode int = 401

/*AddResourceUnauthorized Unauthorized

swagger:response addResourceUnauthorized
*/
type AddResourceUnauthorized struct {
}

// NewAddResourceUnauthorized creates AddResourceUnauthorized with default headers values
func NewAddResourceUnauthorized() *AddResourceUnauthorized {

	return &AddResourceUnauthorized{}
}

// WriteResponse to the client
func (o *AddResourceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// AddResourceNotFoundCode is the HTTP code returned for type AddResourceNotFound
const AddResourceNotFoundCode int = 404

/*AddResourceNotFound resource not found

swagger:response addResourceNotFound
*/
type AddResourceNotFound struct {

	/*
	  In: Body
	*/
	Payload *AddResourceNotFoundBody `json:"body,omitempty"`
}

// NewAddResourceNotFound creates AddResourceNotFound with default headers values
func NewAddResourceNotFound() *AddResourceNotFound {

	return &AddResourceNotFound{}
}

// WithPayload adds the payload to the add resource not found response
func (o *AddResourceNotFound) WithPayload(payload *AddResourceNotFoundBody) *AddResourceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add resource not found response
func (o *AddResourceNotFound) SetPayload(payload *AddResourceNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddResourceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
