// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"tides-server/pkg/models"
)

// ResourceVsphereInfoHandlerFunc turns a function with the right signature into a resource vsphere info handler
type ResourceVsphereInfoHandlerFunc func(ResourceVsphereInfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ResourceVsphereInfoHandlerFunc) Handle(params ResourceVsphereInfoParams) middleware.Responder {
	return fn(params)
}

// ResourceVsphereInfoHandler interface for that can handle valid resource vsphere info params
type ResourceVsphereInfoHandler interface {
	Handle(ResourceVsphereInfoParams) middleware.Responder
}

// NewResourceVsphereInfo creates a new http.Handler for the resource vsphere info operation
func NewResourceVsphereInfo(ctx *middleware.Context, handler ResourceVsphereInfoHandler) *ResourceVsphereInfo {
	return &ResourceVsphereInfo{Context: ctx, Handler: handler}
}

/*ResourceVsphereInfo swagger:route GET /resource/vsphere/get_details resource resourceVsphereInfo

returns detailed info of resources belonging to a user

*/
type ResourceVsphereInfo struct {
	Context *middleware.Context
	Handler ResourceVsphereInfoHandler
}

func (o *ResourceVsphereInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewResourceVsphereInfoParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ResourceVsphereInfoNotFoundBody resource vsphere info not found body
//
// swagger:model ResourceVsphereInfoNotFoundBody
type ResourceVsphereInfoNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this resource vsphere info not found body
func (o *ResourceVsphereInfoNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ResourceVsphereInfoNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ResourceVsphereInfoNotFoundBody) UnmarshalBinary(b []byte) error {
	var res ResourceVsphereInfoNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// ResourceVsphereInfoOKBody resource vsphere info o k body
//
// swagger:model ResourceVsphereInfoOKBody
type ResourceVsphereInfoOKBody struct {

	// message
	Message string `json:"message,omitempty"`

	// results
	Results []*models.ResourceInfoItem `json:"results"`
}

// Validate validates this resource vsphere info o k body
func (o *ResourceVsphereInfoOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ResourceVsphereInfoOKBody) validateResults(formats strfmt.Registry) error {

	if swag.IsZero(o.Results) { // not required
		return nil
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resourceVsphereInfoOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ResourceVsphereInfoOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ResourceVsphereInfoOKBody) UnmarshalBinary(b []byte) error {
	var res ResourceVsphereInfoOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
