// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"tides-server/pkg/models"
)

// ResourceVMsInfoHandlerFunc turns a function with the right signature into a resource v ms info handler
type ResourceVMsInfoHandlerFunc func(ResourceVMsInfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ResourceVMsInfoHandlerFunc) Handle(params ResourceVMsInfoParams) middleware.Responder {
	return fn(params)
}

// ResourceVMsInfoHandler interface for that can handle valid resource v ms info params
type ResourceVMsInfoHandler interface {
	Handle(ResourceVMsInfoParams) middleware.Responder
}

// NewResourceVMsInfo creates a new http.Handler for the resource v ms info operation
func NewResourceVMsInfo(ctx *middleware.Context, handler ResourceVMsInfoHandler) *ResourceVMsInfo {
	return &ResourceVMsInfo{Context: ctx, Handler: handler}
}

/*ResourceVMsInfo swagger:route GET /resource/get_vm_details resource resourceVMsInfo

get detailed info of VMs belonging to a user

*/
type ResourceVMsInfo struct {
	Context *middleware.Context
	Handler ResourceVMsInfoHandler
}

func (o *ResourceVMsInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewResourceVMsInfoParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ResourceVMsInfoNotFoundBody resource v ms info not found body
//
// swagger:model ResourceVMsInfoNotFoundBody
type ResourceVMsInfoNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this resource v ms info not found body
func (o *ResourceVMsInfoNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ResourceVMsInfoNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ResourceVMsInfoNotFoundBody) UnmarshalBinary(b []byte) error {
	var res ResourceVMsInfoNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// ResourceVMsInfoOKBody resource v ms info o k body
//
// swagger:model ResourceVMsInfoOKBody
type ResourceVMsInfoOKBody struct {

	// message
	Message string `json:"message,omitempty"`

	// results
	Results [][]*models.ResourceVMInfoItem `json:"results"`
}

// Validate validates this resource v ms info o k body
func (o *ResourceVMsInfoOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ResourceVMsInfoOKBody) validateResults(formats strfmt.Registry) error {

	if swag.IsZero(o.Results) { // not required
		return nil
	}

	for i := 0; i < len(o.Results); i++ {

		for ii := 0; ii < len(o.Results[i]); ii++ {
			if swag.IsZero(o.Results[i][ii]) { // not required
				continue
			}

			if o.Results[i][ii] != nil {
				if err := o.Results[i][ii].Validate(formats); err != nil {
					if ve, ok := err.(*errors.Validation); ok {
						return ve.ValidateName("resourceVMsInfoOK" + "." + "results" + "." + strconv.Itoa(i) + "." + strconv.Itoa(ii))
					}
					return err
				}
			}

		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ResourceVMsInfoOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ResourceVMsInfoOKBody) UnmarshalBinary(b []byte) error {
	var res ResourceVMsInfoOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
