// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"tides-server/pkg/models"
)

// ResourceVsphereVMsInfoHandlerFunc turns a function with the right signature into a resource vsphere v ms info handler
type ResourceVsphereVMsInfoHandlerFunc func(ResourceVsphereVMsInfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ResourceVsphereVMsInfoHandlerFunc) Handle(params ResourceVsphereVMsInfoParams) middleware.Responder {
	return fn(params)
}

// ResourceVsphereVMsInfoHandler interface for that can handle valid resource vsphere v ms info params
type ResourceVsphereVMsInfoHandler interface {
	Handle(ResourceVsphereVMsInfoParams) middleware.Responder
}

// NewResourceVsphereVMsInfo creates a new http.Handler for the resource vsphere v ms info operation
func NewResourceVsphereVMsInfo(ctx *middleware.Context, handler ResourceVsphereVMsInfoHandler) *ResourceVsphereVMsInfo {
	return &ResourceVsphereVMsInfo{Context: ctx, Handler: handler}
}

/*ResourceVsphereVMsInfo swagger:route GET /resource/vsphere/get_vm_details resource resourceVsphereVMsInfo

get detailed info of VMs belonging to a user

*/
type ResourceVsphereVMsInfo struct {
	Context *middleware.Context
	Handler ResourceVsphereVMsInfoHandler
}

func (o *ResourceVsphereVMsInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewResourceVsphereVMsInfoParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ResourceVsphereVMsInfoNotFoundBody resource vsphere v ms info not found body
//
// swagger:model ResourceVsphereVMsInfoNotFoundBody
type ResourceVsphereVMsInfoNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this resource vsphere v ms info not found body
func (o *ResourceVsphereVMsInfoNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ResourceVsphereVMsInfoNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ResourceVsphereVMsInfoNotFoundBody) UnmarshalBinary(b []byte) error {
	var res ResourceVsphereVMsInfoNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// ResourceVsphereVMsInfoOKBody resource vsphere v ms info o k body
//
// swagger:model ResourceVsphereVMsInfoOKBody
type ResourceVsphereVMsInfoOKBody struct {

	// message
	Message string `json:"message,omitempty"`

	// results
	Results [][]*models.ResourceVMInfoItem `json:"results"`
}

// Validate validates this resource vsphere v ms info o k body
func (o *ResourceVsphereVMsInfoOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ResourceVsphereVMsInfoOKBody) validateResults(formats strfmt.Registry) error {

	if swag.IsZero(o.Results) { // not required
		return nil
	}

	for i := 0; i < len(o.Results); i++ {

		for ii := 0; ii < len(o.Results[i]); ii++ {
			if swag.IsZero(o.Results[i][ii]) { // not required
				continue
			}

			if o.Results[i][ii] != nil {
				if err := o.Results[i][ii].Validate(formats); err != nil {
					if ve, ok := err.(*errors.Validation); ok {
						return ve.ValidateName("resourceVsphereVMsInfoOK" + "." + "results" + "." + strconv.Itoa(i) + "." + strconv.Itoa(ii))
					}
					return err
				}
			}

		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ResourceVsphereVMsInfoOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ResourceVsphereVMsInfoOKBody) UnmarshalBinary(b []byte) error {
	var res ResourceVsphereVMsInfoOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
