// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewVsphereOverviewStatsParams creates a new VsphereOverviewStatsParams object
// no default values defined in spec.
func NewVsphereOverviewStatsParams() VsphereOverviewStatsParams {

	return VsphereOverviewStatsParams{}
}

// VsphereOverviewStatsParams contains all the bound params for the vsphere overview stats operation
// typically these are obtained from a http.Request
//
// swagger:parameters vsphereOverviewStats
type VsphereOverviewStatsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewVsphereOverviewStatsParams() beforehand.
func (o *VsphereOverviewStatsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
