// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// VsphereOverviewStatsOKCode is the HTTP code returned for type VsphereOverviewStatsOK
const VsphereOverviewStatsOKCode int = 200

/*VsphereOverviewStatsOK returns overall contribution statistics for a user

swagger:response vsphereOverviewStatsOK
*/
type VsphereOverviewStatsOK struct {

	/*
	  In: Body
	*/
	Payload *VsphereOverviewStatsOKBody `json:"body,omitempty"`
}

// NewVsphereOverviewStatsOK creates VsphereOverviewStatsOK with default headers values
func NewVsphereOverviewStatsOK() *VsphereOverviewStatsOK {

	return &VsphereOverviewStatsOK{}
}

// WithPayload adds the payload to the vsphere overview stats o k response
func (o *VsphereOverviewStatsOK) WithPayload(payload *VsphereOverviewStatsOKBody) *VsphereOverviewStatsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the vsphere overview stats o k response
func (o *VsphereOverviewStatsOK) SetPayload(payload *VsphereOverviewStatsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VsphereOverviewStatsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// VsphereOverviewStatsUnauthorizedCode is the HTTP code returned for type VsphereOverviewStatsUnauthorized
const VsphereOverviewStatsUnauthorizedCode int = 401

/*VsphereOverviewStatsUnauthorized Unauthorized

swagger:response vsphereOverviewStatsUnauthorized
*/
type VsphereOverviewStatsUnauthorized struct {
}

// NewVsphereOverviewStatsUnauthorized creates VsphereOverviewStatsUnauthorized with default headers values
func NewVsphereOverviewStatsUnauthorized() *VsphereOverviewStatsUnauthorized {

	return &VsphereOverviewStatsUnauthorized{}
}

// WriteResponse to the client
func (o *VsphereOverviewStatsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// VsphereOverviewStatsNotFoundCode is the HTTP code returned for type VsphereOverviewStatsNotFound
const VsphereOverviewStatsNotFoundCode int = 404

/*VsphereOverviewStatsNotFound resource not found

swagger:response vsphereOverviewStatsNotFound
*/
type VsphereOverviewStatsNotFound struct {

	/*
	  In: Body
	*/
	Payload *VsphereOverviewStatsNotFoundBody `json:"body,omitempty"`
}

// NewVsphereOverviewStatsNotFound creates VsphereOverviewStatsNotFound with default headers values
func NewVsphereOverviewStatsNotFound() *VsphereOverviewStatsNotFound {

	return &VsphereOverviewStatsNotFound{}
}

// WithPayload adds the payload to the vsphere overview stats not found response
func (o *VsphereOverviewStatsNotFound) WithPayload(payload *VsphereOverviewStatsNotFoundBody) *VsphereOverviewStatsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the vsphere overview stats not found response
func (o *VsphereOverviewStatsNotFound) SetPayload(payload *VsphereOverviewStatsNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VsphereOverviewStatsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
