// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ResourceAddItem resource add item
//
// swagger:model ResourceAddItem
type ResourceAddItem struct {

	// CPU percent
	CPUPercent float64 `json:"CPUPercent,omitempty"`

	// RAM percent
	RAMPercent float64 `json:"RAMPercent,omitempty"`

	// cluster
	Cluster string `json:"cluster,omitempty"`

	// current CPU
	CurrentCPU float64 `json:"currentCPU,omitempty"`

	// current RAM
	CurrentRAM float64 `json:"currentRAM,omitempty"`

	// datacenter
	Datacenter string `json:"datacenter,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// is active
	IsActive bool `json:"isActive,omitempty"`

	// is resource pool
	IsResourcePool bool `json:"isResourcePool,omitempty"`

	// job completed
	JobCompleted int64 `json:"jobCompleted,omitempty"`

	// monitored
	Monitored bool `json:"monitored,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// platform type
	// Enum: [vsphere kvm hyper-v]
	PlatformType string `json:"platformType,omitempty"`

	// policy name
	PolicyName string `json:"policyName,omitempty"`

	// status
	// Enum: [idle normal busy unknown]
	Status string `json:"status,omitempty"`

	// total CPU
	TotalCPU float64 `json:"totalCPU,omitempty"`

	// total jobs
	TotalJobs int64 `json:"totalJobs,omitempty"`

	// total RAM
	TotalRAM float64 `json:"totalRAM,omitempty"`
}

// Validate validates this resource add item
func (m *ResourceAddItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlatformType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var resourceAddItemTypePlatformTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["vsphere","kvm","hyper-v"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		resourceAddItemTypePlatformTypePropEnum = append(resourceAddItemTypePlatformTypePropEnum, v)
	}
}

const (

	// ResourceAddItemPlatformTypeVsphere captures enum value "vsphere"
	ResourceAddItemPlatformTypeVsphere string = "vsphere"

	// ResourceAddItemPlatformTypeKvm captures enum value "kvm"
	ResourceAddItemPlatformTypeKvm string = "kvm"

	// ResourceAddItemPlatformTypeHyperv captures enum value "hyper-v"
	ResourceAddItemPlatformTypeHyperv string = "hyper-v"
)

// prop value enum
func (m *ResourceAddItem) validatePlatformTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, resourceAddItemTypePlatformTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ResourceAddItem) validatePlatformType(formats strfmt.Registry) error {

	if swag.IsZero(m.PlatformType) { // not required
		return nil
	}

	// value enum
	if err := m.validatePlatformTypeEnum("platformType", "body", m.PlatformType); err != nil {
		return err
	}

	return nil
}

var resourceAddItemTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["idle","normal","busy","unknown"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		resourceAddItemTypeStatusPropEnum = append(resourceAddItemTypeStatusPropEnum, v)
	}
}

const (

	// ResourceAddItemStatusIdle captures enum value "idle"
	ResourceAddItemStatusIdle string = "idle"

	// ResourceAddItemStatusNormal captures enum value "normal"
	ResourceAddItemStatusNormal string = "normal"

	// ResourceAddItemStatusBusy captures enum value "busy"
	ResourceAddItemStatusBusy string = "busy"

	// ResourceAddItemStatusUnknown captures enum value "unknown"
	ResourceAddItemStatusUnknown string = "unknown"
)

// prop value enum
func (m *ResourceAddItem) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, resourceAddItemTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ResourceAddItem) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResourceAddItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceAddItem) UnmarshalBinary(b []byte) error {
	var res ResourceAddItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
