// Code generated by go-swagger; DO NOT EDIT.

package usage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddHostUsageOKCode is the HTTP code returned for type AddHostUsageOK
const AddHostUsageOKCode int = 200

/*AddHostUsageOK OK

swagger:response addHostUsageOK
*/
type AddHostUsageOK struct {

	/*
	  In: Body
	*/
	Payload *AddHostUsageOKBody `json:"body,omitempty"`
}

// NewAddHostUsageOK creates AddHostUsageOK with default headers values
func NewAddHostUsageOK() *AddHostUsageOK {

	return &AddHostUsageOK{}
}

// WithPayload adds the payload to the add host usage o k response
func (o *AddHostUsageOK) WithPayload(payload *AddHostUsageOKBody) *AddHostUsageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add host usage o k response
func (o *AddHostUsageOK) SetPayload(payload *AddHostUsageOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddHostUsageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddHostUsageBadRequestCode is the HTTP code returned for type AddHostUsageBadRequest
const AddHostUsageBadRequestCode int = 400

/*AddHostUsageBadRequest bad request

swagger:response addHostUsageBadRequest
*/
type AddHostUsageBadRequest struct {
}

// NewAddHostUsageBadRequest creates AddHostUsageBadRequest with default headers values
func NewAddHostUsageBadRequest() *AddHostUsageBadRequest {

	return &AddHostUsageBadRequest{}
}

// WriteResponse to the client
func (o *AddHostUsageBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddHostUsageNotFoundCode is the HTTP code returned for type AddHostUsageNotFound
const AddHostUsageNotFoundCode int = 404

/*AddHostUsageNotFound resource not found

swagger:response addHostUsageNotFound
*/
type AddHostUsageNotFound struct {
}

// NewAddHostUsageNotFound creates AddHostUsageNotFound with default headers values
func NewAddHostUsageNotFound() *AddHostUsageNotFound {

	return &AddHostUsageNotFound{}
}

// WriteResponse to the client
func (o *AddHostUsageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
