// Code generated by go-swagger; DO NOT EDIT.

package usage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"encoding/json"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddHostUsageHandlerFunc turns a function with the right signature into a add host usage handler
type AddHostUsageHandlerFunc func(AddHostUsageParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddHostUsageHandlerFunc) Handle(params AddHostUsageParams) middleware.Responder {
	return fn(params)
}

// AddHostUsageHandler interface for that can handle valid add host usage params
type AddHostUsageHandler interface {
	Handle(AddHostUsageParams) middleware.Responder
}

// NewAddHostUsage creates a new http.Handler for the add host usage operation
func NewAddHostUsage(ctx *middleware.Context, handler AddHostUsageHandler) *AddHostUsage {
	return &AddHostUsage{Context: ctx, Handler: handler}
}

/*AddHostUsage swagger:route POST /usage/addHost usage addHostUsage

add host usage info into database

*/
type AddHostUsage struct {
	Context *middleware.Context
	Handler AddHostUsageHandler
}

func (o *AddHostUsage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddHostUsageParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// AddHostUsageBody add host usage body
//
// swagger:model AddHostUsageBody
type AddHostUsageBody struct {

	// current CPU
	CurrentCPU float64 `json:"currentCPU,omitempty"`

	// current RAM
	CurrentRAM float64 `json:"currentRAM,omitempty"`

	// host address
	HostAddress string `json:"hostAddress,omitempty"`

	// host name
	HostName string `json:"hostName,omitempty"`

	// total CPU
	TotalCPU float64 `json:"totalCPU,omitempty"`

	// total RAM
	TotalRAM float64 `json:"totalRAM,omitempty"`
}

// Validate validates this add host usage body
func (o *AddHostUsageBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AddHostUsageBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AddHostUsageBody) UnmarshalBinary(b []byte) error {
	var res AddHostUsageBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// AddHostUsageOKBody add host usage o k body
//
// swagger:model AddHostUsageOKBody
type AddHostUsageOKBody struct {

	// message
	// Enum: [success]
	Message string `json:"message,omitempty"`
}

// Validate validates this add host usage o k body
func (o *AddHostUsageOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var addHostUsageOKBodyTypeMessagePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["success"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		addHostUsageOKBodyTypeMessagePropEnum = append(addHostUsageOKBodyTypeMessagePropEnum, v)
	}
}

const (

	// AddHostUsageOKBodyMessageSuccess captures enum value "success"
	AddHostUsageOKBodyMessageSuccess string = "success"
)

// prop value enum
func (o *AddHostUsageOKBody) validateMessageEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, addHostUsageOKBodyTypeMessagePropEnum); err != nil {
		return err
	}
	return nil
}

func (o *AddHostUsageOKBody) validateMessage(formats strfmt.Registry) error {

	if swag.IsZero(o.Message) { // not required
		return nil
	}

	// value enum
	if err := o.validateMessageEnum("addHostUsageOK"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *AddHostUsageOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AddHostUsageOKBody) UnmarshalBinary(b []byte) error {
	var res AddHostUsageOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
