// Code generated by go-swagger; DO NOT EDIT.

package usage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteResourceUsageOKCode is the HTTP code returned for type DeleteResourceUsageOK
const DeleteResourceUsageOKCode int = 200

/*DeleteResourceUsageOK OK

swagger:response deleteResourceUsageOK
*/
type DeleteResourceUsageOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteResourceUsageOKBody `json:"body,omitempty"`
}

// NewDeleteResourceUsageOK creates DeleteResourceUsageOK with default headers values
func NewDeleteResourceUsageOK() *DeleteResourceUsageOK {

	return &DeleteResourceUsageOK{}
}

// WithPayload adds the payload to the delete resource usage o k response
func (o *DeleteResourceUsageOK) WithPayload(payload *DeleteResourceUsageOKBody) *DeleteResourceUsageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource usage o k response
func (o *DeleteResourceUsageOK) SetPayload(payload *DeleteResourceUsageOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceUsageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResourceUsageBadRequestCode is the HTTP code returned for type DeleteResourceUsageBadRequest
const DeleteResourceUsageBadRequestCode int = 400

/*DeleteResourceUsageBadRequest bad request

swagger:response deleteResourceUsageBadRequest
*/
type DeleteResourceUsageBadRequest struct {
}

// NewDeleteResourceUsageBadRequest creates DeleteResourceUsageBadRequest with default headers values
func NewDeleteResourceUsageBadRequest() *DeleteResourceUsageBadRequest {

	return &DeleteResourceUsageBadRequest{}
}

// WriteResponse to the client
func (o *DeleteResourceUsageBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteResourceUsageNotFoundCode is the HTTP code returned for type DeleteResourceUsageNotFound
const DeleteResourceUsageNotFoundCode int = 404

/*DeleteResourceUsageNotFound resource not found

swagger:response deleteResourceUsageNotFound
*/
type DeleteResourceUsageNotFound struct {
}

// NewDeleteResourceUsageNotFound creates DeleteResourceUsageNotFound with default headers values
func NewDeleteResourceUsageNotFound() *DeleteResourceUsageNotFound {

	return &DeleteResourceUsageNotFound{}
}

// WriteResponse to the client
func (o *DeleteResourceUsageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
