// Code generated by go-swagger; DO NOT EDIT.

package usage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteHostUsageOKCode is the HTTP code returned for type DeleteHostUsageOK
const DeleteHostUsageOKCode int = 200

/*DeleteHostUsageOK OK

swagger:response deleteHostUsageOK
*/
type DeleteHostUsageOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteHostUsageOKBody `json:"body,omitempty"`
}

// NewDeleteHostUsageOK creates DeleteHostUsageOK with default headers values
func NewDeleteHostUsageOK() *DeleteHostUsageOK {

	return &DeleteHostUsageOK{}
}

// WithPayload adds the payload to the delete host usage o k response
func (o *DeleteHostUsageOK) WithPayload(payload *DeleteHostUsageOKBody) *DeleteHostUsageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete host usage o k response
func (o *DeleteHostUsageOK) SetPayload(payload *DeleteHostUsageOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHostUsageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteHostUsageBadRequestCode is the HTTP code returned for type DeleteHostUsageBadRequest
const DeleteHostUsageBadRequestCode int = 400

/*DeleteHostUsageBadRequest bad request

swagger:response deleteHostUsageBadRequest
*/
type DeleteHostUsageBadRequest struct {
}

// NewDeleteHostUsageBadRequest creates DeleteHostUsageBadRequest with default headers values
func NewDeleteHostUsageBadRequest() *DeleteHostUsageBadRequest {

	return &DeleteHostUsageBadRequest{}
}

// WriteResponse to the client
func (o *DeleteHostUsageBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteHostUsageNotFoundCode is the HTTP code returned for type DeleteHostUsageNotFound
const DeleteHostUsageNotFoundCode int = 404

/*DeleteHostUsageNotFound resource not found

swagger:response deleteHostUsageNotFound
*/
type DeleteHostUsageNotFound struct {
}

// NewDeleteHostUsageNotFound creates DeleteHostUsageNotFound with default headers values
func NewDeleteHostUsageNotFound() *DeleteHostUsageNotFound {

	return &DeleteHostUsageNotFound{}
}

// WriteResponse to the client
func (o *DeleteHostUsageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
