# Generated by Django 2.2.7 on 2019-12-08 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template', '0001_initial'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('host_address', models.TextField()),
                ('host_name', models.TextField()),
                ('name', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('is_destroy', models.BooleanField(blank=True, default=False, null=True)),
                ('deploy_type', models.CharField(choices=[('1', 'kubernetes'), ('2', 'vm')], default='vm', max_length=20)),
                ('idle_policy', models.TextField(blank=True, null=True)),
                ('busy_policy', models.TextField(blank=True, null=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('project_url', models.TextField()),
                ('boinc_user', models.TextField()),
                ('boinc_password', models.TextField()),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='resource.Resource')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='template.Template')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tides Policy',
                'verbose_name_plural': 'Tides Policies',
            },
        ),
    ]
