# Generated by Django 2.2.7 on 2019-12-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_address', models.TextField()),
                ('host_name', models.TextField(unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('is_destroy', models.BooleanField(blank=True, default=False, null=True)),
                ('deploy_type', models.CharField(choices=[('1', 'kubernetes'), ('2', 'vm')], default='vm', max_length=20)),
                ('idle_policy', models.TextField(blank=True, null=True)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.Resource')),
            ],
            options={
                'verbose_name': 'Tides Policy',
                'verbose_name_plural': 'Tides Policies',
            },
        ),
    ]
