# Generated by Django 2.2.7 on 2019-12-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='is_destroy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
