# Generated by Django 2.2.7 on 2019-12-03 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_auto_20191203_2238'),
        ('policy', '0002_auto_20191201_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='host_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='host_name',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.Resource'),
        ),
    ]
