// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "CloudTides-Server",
    "version": "0.0.1"
  },
  "basePath": "/v1",
  "paths": {
    "/policy/add": {
      "post": {
        "description": "add a new idle policy and threshold policy",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "policy"
        ],
        "operationId": "addPolicy",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "accountType": {
                  "type": "string",
                  "enum": [
                    "accManager",
                    "boinc"
                  ]
                },
                "deployType": {
                  "type": "string",
                  "enum": [
                    "K8S",
                    "VM"
                  ]
                },
                "idle": {
                  "type": "string"
                },
                "isDestroy": {
                  "type": "boolean"
                },
                "name": {
                  "type": "string"
                },
                "projectId": {
                  "type": "integer"
                },
                "templateId": {
                  "type": "integer"
                },
                "threshold": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/policy/list": {
      "get": {
        "description": "list policies belonging to a user",
        "produces": [
          "application/json"
        ],
        "tags": [
          "policy"
        ],
        "operationId": "listPolicy",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "deployType": {
                        "type": "string",
                        "enum": [
                          "K8S",
                          "VM"
                        ]
                      },
                      "hostsAssigned": {
                        "type": "integer"
                      },
                      "id": {
                        "type": "integer"
                      },
                      "idlePolicy": {
                        "type": "string"
                      },
                      "isDestroy": {
                        "type": "boolean"
                      },
                      "name": {
                        "type": "string"
                      },
                      "projectName": {
                        "type": "string"
                      },
                      "thresholdPolicy": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/policy/remove": {
      "delete": {
        "description": "remove a policy",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "policy"
        ],
        "operationId": "removePolicy",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "no matching objects"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/policy/update": {
      "put": {
        "description": "update a policy",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "policy"
        ],
        "operationId": "updatePolicy",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "Id": {
                  "type": "integer"
                },
                "accountType": {
                  "type": "string",
                  "enum": [
                    "accManager",
                    "boinc"
                  ]
                },
                "deployType": {
                  "type": "string",
                  "enum": [
                    "K8S",
                    "VM"
                  ]
                },
                "idle": {
                  "type": "string"
                },
                "isDestroy": {
                  "type": "boolean"
                },
                "name": {
                  "type": "string"
                },
                "projectId": {
                  "type": "integer"
                },
                "templateId": {
                  "type": "integer"
                },
                "threshold": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/resource/add": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "addResource",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "datacenters": {
                  "type": "string"
                },
                "host": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "policy": {
                  "type": "integer"
                },
                "username": {
                  "type": "string"
                },
                "vmtype": {
                  "type": "string",
                  "enum": [
                    "vsphere",
                    "kvm",
                    "hyper-v"
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns the list of created resources",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ResourceAddItem"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/assign_policy": {
      "put": {
        "description": "assign a policy to a specified resource",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "assignPolicy",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "policyId": {
                  "type": "integer"
                },
                "resourceId": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns success message",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/delete": {
      "delete": {
        "description": "delete specified resource",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "deleteResource",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns success message",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/destroy_vm": {
      "put": {
        "description": "destroy specified VM",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "destroyVM",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ipAddress": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns success message",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/get_details": {
      "get": {
        "description": "returns detailed info of resources belonging to a user",
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "resourceInfo",
        "responses": {
          "200": {
            "description": "returns detailed info of resources belonging to a user",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ResourceInfoItem"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/get_vm_details": {
      "get": {
        "description": "get detailed info of VMs belonging to a user",
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "resourceVMsInfo",
        "responses": {
          "200": {
            "description": "get detailed info of VMs belonging to a user",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ResourceVMInfoItem"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/list": {
      "get": {
        "description": "returns the list of resources belonging to a user",
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "listResource",
        "responses": {
          "200": {
            "description": "returns the list of resources belonging to a user",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ResourceListItem"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/resource/overview": {
      "get": {
        "description": "returns overall contribution statistics for a user",
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "overviewStats",
        "responses": {
          "200": {
            "description": "returns overall contribution statistics for a user",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "object",
                  "properties": {
                    "contribution": {
                      "type": "number"
                    },
                    "power": {
                      "type": "number"
                    },
                    "resource": {
                      "type": "object",
                      "properties": {
                        "contributing": {
                          "type": "integer"
                        },
                        "hosts": {
                          "type": "integer"
                        },
                        "vms": {
                          "type": "integer"
                        }
                      }
                    },
                    "workload": {
                      "type": "object",
                      "properties": {
                        "contributed": {
                          "type": "integer"
                        },
                        "destroyed": {
                          "type": "integer"
                        },
                        "hostsUsed": {
                          "type": "integer"
                        },
                        "running": {
                          "type": "integer"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/toggle_active": {
      "put": {
        "description": "toggle the status of the resource",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "toggleActive",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns success message",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resouce not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/update": {
      "put": {
        "description": "update usage info of host",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "updateHost",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "currentCPU": {
                  "type": "number"
                },
                "currentRAM": {
                  "type": "number"
                },
                "hostAddress": {
                  "type": "string"
                },
                "hostName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns success message",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/validate": {
      "get": {
        "description": "returns the list of data centers belonging to the host",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "validateResource",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "host": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns the list of data centers belonging to the host",
            "schema": {
              "description": "list of data centers belonging to the host",
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/template/add": {
      "post": {
        "description": "upload a VM template",
        "consumes": [
          "application/json",
          "multipart/form-data"
        ],
        "tags": [
          "template"
        ],
        "operationId": "addTemplate",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "compat": {
                  "type": "string"
                },
                "memsize": {
                  "type": "number"
                },
                "os": {
                  "type": "string"
                },
                "source": {
                  "type": "string"
                },
                "space": {
                  "type": "number"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/template/delete": {
      "delete": {
        "description": "delete specified template",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "template"
        ],
        "operationId": "deleteTemplate",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/template/list": {
      "get": {
        "description": "list all available VM templates",
        "tags": [
          "template"
        ],
        "operationId": "listTemplate",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                },
                "results": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "compatibility": {
                        "type": "string"
                      },
                      "dateAdded": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "guestOS": {
                        "type": "string"
                      },
                      "memorySize": {
                        "type": "number"
                      },
                      "name": {
                        "type": "string"
                      },
                      "provisionedSpace": {
                        "type": "number"
                      },
                      "templateType": {
                        "type": "string",
                        "enum": [
                          "datastore",
                          "upload"
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          }
        }
      }
    },
    "/usage/addHost": {
      "post": {
        "description": "add host usage info into database",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "usage"
        ],
        "operationId": "addHostUsage",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "currentCPU": {
                  "type": "number"
                },
                "currentRAM": {
                  "type": "number"
                },
                "hostAddress": {
                  "type": "string"
                },
                "hostName": {
                  "type": "string"
                },
                "totalCPU": {
                  "type": "number"
                },
                "totalRAM": {
                  "type": "number"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/usage/addVM": {
      "post": {
        "description": "add VM usage info into database",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "usage"
        ],
        "operationId": "addVMUsage",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "object",
                "properties": {
                  "boincStartTime": {
                    "type": "string"
                  },
                  "currentCPU": {
                    "type": "number"
                  },
                  "currentRAM": {
                    "type": "number"
                  },
                  "dcName": {
                    "type": "string"
                  },
                  "guestOS": {
                    "type": "string"
                  },
                  "hostName": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "numCPU": {
                    "type": "integer"
                  },
                  "poweredOn": {
                    "type": "boolean"
                  },
                  "totalCPU": {
                    "type": "number"
                  },
                  "totalRAM": {
                    "type": "number"
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          }
        }
      }
    },
    "/usage/deleteHost": {
      "delete": {
        "description": "delete host usage info",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "usage"
        ],
        "operationId": "deleteHostUsage",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "hostAddress": {
                  "type": "string"
                },
                "hostName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/usage/getUsage": {
      "get": {
        "description": "get host usage info during last period",
        "tags": [
          "usage"
        ],
        "operationId": "hostPastUsage",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "bad request"
          }
        }
      }
    },
    "/usage/updateHost": {
      "put": {
        "description": "update host usage info",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "usage"
        ],
        "operationId": "updateHostUsage",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "currentCPU": {
                  "type": "number"
                },
                "currentRAM": {
                  "type": "number"
                },
                "hostAddress": {
                  "type": "string"
                },
                "hostName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "host usage recorded"
                  ]
                }
              }
            }
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/users/get_details": {
      "get": {
        "description": "get user profile",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "operationId": "userDetails",
        "responses": {
          "200": {
            "description": "returns user profile",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "object",
                  "properties": {
                    "city": {
                      "type": "string"
                    },
                    "companyName": {
                      "type": "string"
                    },
                    "country": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "firstName": {
                      "type": "string"
                    },
                    "lastName": {
                      "type": "string"
                    },
                    "position": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "description": "user login",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "operationId": "userLogin",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "password": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns user info",
            "schema": {
              "type": "object",
              "properties": {
                "token": {
                  "type": "string"
                },
                "userInfo": {
                  "type": "object",
                  "properties": {
                    "priority": {
                      "type": "string",
                      "enum": [
                        "Low",
                        "Medium",
                        "High"
                      ]
                    },
                    "username": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "Unauthorized"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/users/register": {
      "post": {
        "description": "user registration",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "operationId": "registerUser",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "companyName": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "priority": {
                  "type": "string",
                  "enum": [
                    "Low",
                    "Medium",
                    "High"
                  ]
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "userInfo": {
                  "type": "object",
                  "properties": {
                    "companyName": {
                      "type": "string"
                    },
                    "password": {
                      "type": "string"
                    },
                    "priority": {
                      "type": "string",
                      "enum": [
                        "Low",
                        "Medium",
                        "High"
                      ]
                    },
                    "username": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ResourceAddItem": {
      "type": "object",
      "properties": {
        "CPUPercent": {
          "type": "number"
        },
        "RAMPercent": {
          "type": "number"
        },
        "currentCPU": {
          "type": "number"
        },
        "currentRAM": {
          "type": "number"
        },
        "datacenter": {
          "type": "string"
        },
        "hostName": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "isActive": {
          "type": "boolean"
        },
        "jobCompleted": {
          "type": "integer"
        },
        "monitored": {
          "type": "boolean"
        },
        "platformType": {
          "type": "string",
          "enum": [
            "vsphere",
            "kvm",
            "hyper-v"
          ]
        },
        "policyName": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "idle",
            "normal",
            "busy",
            "unknown"
          ]
        },
        "totalCPU": {
          "type": "number"
        },
        "totalJobs": {
          "type": "integer"
        },
        "totalRAM": {
          "type": "number"
        }
      }
    },
    "ResourceInfoItem": {
      "type": "object",
      "properties": {
        "CPUPercent": {
          "type": "number"
        },
        "RAMPercent": {
          "type": "number"
        },
        "activeVMs": {
          "type": "integer"
        },
        "currentCPU": {
          "type": "number"
        },
        "currentRAM": {
          "type": "number"
        },
        "datacenter": {
          "type": "string"
        },
        "dateAdded": {
          "type": "string"
        },
        "hostName": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "isActive": {
          "type": "boolean"
        },
        "jobCompleted": {
          "type": "integer"
        },
        "lastDeployed": {
          "type": "string"
        },
        "monitored": {
          "type": "boolean"
        },
        "platformType": {
          "type": "string",
          "enum": [
            "vsphere",
            "kvm",
            "hyper-v"
          ]
        },
        "policyName": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "idle",
            "normal",
            "busy",
            "unknown"
          ]
        },
        "totalCPU": {
          "type": "number"
        },
        "totalJobs": {
          "type": "integer"
        },
        "totalRAM": {
          "type": "number"
        },
        "totalVMs": {
          "type": "integer"
        }
      }
    },
    "ResourceListItem": {
      "type": "object",
      "properties": {
        "CPUPercent": {
          "type": "number"
        },
        "RAMPercent": {
          "type": "number"
        },
        "currentCPU": {
          "type": "number"
        },
        "currentRAM": {
          "type": "number"
        },
        "datacenter": {
          "type": "string"
        },
        "dateAdded": {
          "type": "string"
        },
        "hostName": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "isActive": {
          "type": "boolean"
        },
        "jobCompleted": {
          "type": "integer"
        },
        "monitored": {
          "type": "boolean"
        },
        "platformType": {
          "type": "string",
          "enum": [
            "vsphere",
            "kvm",
            "hyper-v"
          ]
        },
        "policyName": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "idle",
            "normal",
            "busy",
            "unknown"
          ]
        },
        "totalCPU": {
          "type": "number"
        },
        "totalJobs": {
          "type": "integer"
        },
        "totalRAM": {
          "type": "number"
        }
      }
    },
    "ResourceVMInfoItem": {
      "type": "object",
      "properties": {
        "CPUPercent": {
          "type": "number"
        },
        "RAMPercent": {
          "type": "number"
        },
        "boincTime": {
          "type": "string"
        },
        "currentCPU": {
          "type": "number"
        },
        "currentRAM": {
          "type": "number"
        },
        "dateCreated": {
          "type": "string"
        },
        "dateDestroyed": {
          "type": "string"
        },
        "guestOS": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "ipAddress": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "poweredOn": {
          "type": "boolean"
        },
        "totalCPU": {
          "type": "number"
        },
        "totalRAM": {
          "type": "number"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "CloudTides-Server",
    "version": "0.0.1"
  },
  "basePath": "/v1",
  "paths": {
    "/policy/add": {
      "post": {
        "description": "add a new idle policy and threshold policy",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "policy"
        ],
        "operationId": "addPolicy",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "accountType": {
                  "type": "string",
                  "enum": [
                    "accManager",
                    "boinc"
                  ]
                },
                "deployType": {
                  "type": "string",
                  "enum": [
                    "K8S",
                    "VM"
                  ]
                },
                "idle": {
                  "type": "string"
                },
                "isDestroy": {
                  "type": "boolean"
                },
                "name": {
                  "type": "string"
                },
                "projectId": {
                  "type": "integer"
                },
                "templateId": {
                  "type": "integer"
                },
                "threshold": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/policy/list": {
      "get": {
        "description": "list policies belonging to a user",
        "produces": [
          "application/json"
        ],
        "tags": [
          "policy"
        ],
        "operationId": "listPolicy",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ResultsItems0"
                  }
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/policy/remove": {
      "delete": {
        "description": "remove a policy",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "policy"
        ],
        "operationId": "removePolicy",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "no matching objects"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/policy/update": {
      "put": {
        "description": "update a policy",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "policy"
        ],
        "operationId": "updatePolicy",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "Id": {
                  "type": "integer"
                },
                "accountType": {
                  "type": "string",
                  "enum": [
                    "accManager",
                    "boinc"
                  ]
                },
                "deployType": {
                  "type": "string",
                  "enum": [
                    "K8S",
                    "VM"
                  ]
                },
                "idle": {
                  "type": "string"
                },
                "isDestroy": {
                  "type": "boolean"
                },
                "name": {
                  "type": "string"
                },
                "projectId": {
                  "type": "integer"
                },
                "templateId": {
                  "type": "integer"
                },
                "threshold": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/resource/add": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "addResource",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "datacenters": {
                  "type": "string"
                },
                "host": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "policy": {
                  "type": "integer"
                },
                "username": {
                  "type": "string"
                },
                "vmtype": {
                  "type": "string",
                  "enum": [
                    "vsphere",
                    "kvm",
                    "hyper-v"
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns the list of created resources",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ResourceAddItem"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/assign_policy": {
      "put": {
        "description": "assign a policy to a specified resource",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "assignPolicy",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "policyId": {
                  "type": "integer"
                },
                "resourceId": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns success message",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/delete": {
      "delete": {
        "description": "delete specified resource",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "deleteResource",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns success message",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/destroy_vm": {
      "put": {
        "description": "destroy specified VM",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "destroyVM",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ipAddress": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns success message",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/get_details": {
      "get": {
        "description": "returns detailed info of resources belonging to a user",
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "resourceInfo",
        "responses": {
          "200": {
            "description": "returns detailed info of resources belonging to a user",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ResourceInfoItem"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/get_vm_details": {
      "get": {
        "description": "get detailed info of VMs belonging to a user",
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "resourceVMsInfo",
        "responses": {
          "200": {
            "description": "get detailed info of VMs belonging to a user",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/ResourceVMInfoItem"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/list": {
      "get": {
        "description": "returns the list of resources belonging to a user",
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "listResource",
        "responses": {
          "200": {
            "description": "returns the list of resources belonging to a user",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ResourceListItem"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/resource/overview": {
      "get": {
        "description": "returns overall contribution statistics for a user",
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "overviewStats",
        "responses": {
          "200": {
            "description": "returns overall contribution statistics for a user",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "object",
                  "properties": {
                    "contribution": {
                      "type": "number"
                    },
                    "power": {
                      "type": "number"
                    },
                    "resource": {
                      "type": "object",
                      "properties": {
                        "contributing": {
                          "type": "integer"
                        },
                        "hosts": {
                          "type": "integer"
                        },
                        "vms": {
                          "type": "integer"
                        }
                      }
                    },
                    "workload": {
                      "type": "object",
                      "properties": {
                        "contributed": {
                          "type": "integer"
                        },
                        "destroyed": {
                          "type": "integer"
                        },
                        "hostsUsed": {
                          "type": "integer"
                        },
                        "running": {
                          "type": "integer"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/toggle_active": {
      "put": {
        "description": "toggle the status of the resource",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "toggleActive",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns success message",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resouce not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/update": {
      "put": {
        "description": "update usage info of host",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "updateHost",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "currentCPU": {
                  "type": "number"
                },
                "currentRAM": {
                  "type": "number"
                },
                "hostAddress": {
                  "type": "string"
                },
                "hostName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns success message",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/resource/validate": {
      "get": {
        "description": "returns the list of data centers belonging to the host",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "resource"
        ],
        "operationId": "validateResource",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "host": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns the list of data centers belonging to the host",
            "schema": {
              "description": "list of data centers belonging to the host",
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/template/add": {
      "post": {
        "description": "upload a VM template",
        "consumes": [
          "application/json",
          "multipart/form-data"
        ],
        "tags": [
          "template"
        ],
        "operationId": "addTemplate",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "compat": {
                  "type": "string"
                },
                "memsize": {
                  "type": "number"
                },
                "os": {
                  "type": "string"
                },
                "source": {
                  "type": "string"
                },
                "space": {
                  "type": "number"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/template/delete": {
      "delete": {
        "description": "delete specified template",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "template"
        ],
        "operationId": "deleteTemplate",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/template/list": {
      "get": {
        "description": "list all available VM templates",
        "tags": [
          "template"
        ],
        "operationId": "listTemplate",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ResultsItems0"
                  }
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          }
        }
      }
    },
    "/usage/addHost": {
      "post": {
        "description": "add host usage info into database",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "usage"
        ],
        "operationId": "addHostUsage",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "currentCPU": {
                  "type": "number"
                },
                "currentRAM": {
                  "type": "number"
                },
                "hostAddress": {
                  "type": "string"
                },
                "hostName": {
                  "type": "string"
                },
                "totalCPU": {
                  "type": "number"
                },
                "totalRAM": {
                  "type": "number"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/usage/addVM": {
      "post": {
        "description": "add VM usage info into database",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "usage"
        ],
        "operationId": "addVMUsage",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "additionalProperties": {
                "$ref": "#/definitions/AddVMUsageParamsBodyAnon"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          }
        }
      }
    },
    "/usage/deleteHost": {
      "delete": {
        "description": "delete host usage info",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "usage"
        ],
        "operationId": "deleteHostUsage",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "hostAddress": {
                  "type": "string"
                },
                "hostName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "success"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "bad request"
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/usage/getUsage": {
      "get": {
        "description": "get host usage info during last period",
        "tags": [
          "usage"
        ],
        "operationId": "hostPastUsage",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "bad request"
          }
        }
      }
    },
    "/usage/updateHost": {
      "put": {
        "description": "update host usage info",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "usage"
        ],
        "operationId": "updateHostUsage",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "currentCPU": {
                  "type": "number"
                },
                "currentRAM": {
                  "type": "number"
                },
                "hostAddress": {
                  "type": "string"
                },
                "hostName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "host usage recorded"
                  ]
                }
              }
            }
          },
          "404": {
            "description": "resource not found"
          }
        }
      }
    },
    "/users/get_details": {
      "get": {
        "description": "get user profile",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "operationId": "userDetails",
        "responses": {
          "200": {
            "description": "returns user profile",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "object",
                  "properties": {
                    "city": {
                      "type": "string"
                    },
                    "companyName": {
                      "type": "string"
                    },
                    "country": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "firstName": {
                      "type": "string"
                    },
                    "lastName": {
                      "type": "string"
                    },
                    "position": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "resource not found",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "description": "user login",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "operationId": "userLogin",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "password": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns user info",
            "schema": {
              "type": "object",
              "properties": {
                "token": {
                  "type": "string"
                },
                "userInfo": {
                  "type": "object",
                  "properties": {
                    "priority": {
                      "type": "string",
                      "enum": [
                        "Low",
                        "Medium",
                        "High"
                      ]
                    },
                    "username": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "enum": [
                    "Unauthorized"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/users/register": {
      "post": {
        "description": "user registration",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "operationId": "registerUser",
        "parameters": [
          {
            "name": "reqBody",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "companyName": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "priority": {
                  "type": "string",
                  "enum": [
                    "Low",
                    "Medium",
                    "High"
                  ]
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "userInfo": {
                  "type": "object",
                  "properties": {
                    "companyName": {
                      "type": "string"
                    },
                    "password": {
                      "type": "string"
                    },
                    "priority": {
                      "type": "string",
                      "enum": [
                        "Low",
                        "Medium",
                        "High"
                      ]
                    },
                    "username": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AddVMUsageParamsBodyAnon": {
      "type": "object",
      "properties": {
        "boincStartTime": {
          "type": "string"
        },
        "currentCPU": {
          "type": "number"
        },
        "currentRAM": {
          "type": "number"
        },
        "dcName": {
          "type": "string"
        },
        "guestOS": {
          "type": "string"
        },
        "hostName": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "numCPU": {
          "type": "integer"
        },
        "poweredOn": {
          "type": "boolean"
        },
        "totalCPU": {
          "type": "number"
        },
        "totalRAM": {
          "type": "number"
        }
      }
    },
    "OverviewStatsOKBodyResults": {
      "type": "object",
      "properties": {
        "contribution": {
          "type": "number"
        },
        "power": {
          "type": "number"
        },
        "resource": {
          "type": "object",
          "properties": {
            "contributing": {
              "type": "integer"
            },
            "hosts": {
              "type": "integer"
            },
            "vms": {
              "type": "integer"
            }
          }
        },
        "workload": {
          "type": "object",
          "properties": {
            "contributed": {
              "type": "integer"
            },
            "destroyed": {
              "type": "integer"
            },
            "hostsUsed": {
              "type": "integer"
            },
            "running": {
              "type": "integer"
            }
          }
        }
      }
    },
    "OverviewStatsOKBodyResultsResource": {
      "type": "object",
      "properties": {
        "contributing": {
          "type": "integer"
        },
        "hosts": {
          "type": "integer"
        },
        "vms": {
          "type": "integer"
        }
      }
    },
    "OverviewStatsOKBodyResultsWorkload": {
      "type": "object",
      "properties": {
        "contributed": {
          "type": "integer"
        },
        "destroyed": {
          "type": "integer"
        },
        "hostsUsed": {
          "type": "integer"
        },
        "running": {
          "type": "integer"
        }
      }
    },
    "RegisterUserOKBodyUserInfo": {
      "type": "object",
      "properties": {
        "companyName": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "priority": {
          "type": "string",
          "enum": [
            "Low",
            "Medium",
            "High"
          ]
        },
        "username": {
          "type": "string"
        }
      }
    },
    "ResourceAddItem": {
      "type": "object",
      "properties": {
        "CPUPercent": {
          "type": "number"
        },
        "RAMPercent": {
          "type": "number"
        },
        "currentCPU": {
          "type": "number"
        },
        "currentRAM": {
          "type": "number"
        },
        "datacenter": {
          "type": "string"
        },
        "hostName": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "isActive": {
          "type": "boolean"
        },
        "jobCompleted": {
          "type": "integer"
        },
        "monitored": {
          "type": "boolean"
        },
        "platformType": {
          "type": "string",
          "enum": [
            "vsphere",
            "kvm",
            "hyper-v"
          ]
        },
        "policyName": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "idle",
            "normal",
            "busy",
            "unknown"
          ]
        },
        "totalCPU": {
          "type": "number"
        },
        "totalJobs": {
          "type": "integer"
        },
        "totalRAM": {
          "type": "number"
        }
      }
    },
    "ResourceInfoItem": {
      "type": "object",
      "properties": {
        "CPUPercent": {
          "type": "number"
        },
        "RAMPercent": {
          "type": "number"
        },
        "activeVMs": {
          "type": "integer"
        },
        "currentCPU": {
          "type": "number"
        },
        "currentRAM": {
          "type": "number"
        },
        "datacenter": {
          "type": "string"
        },
        "dateAdded": {
          "type": "string"
        },
        "hostName": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "isActive": {
          "type": "boolean"
        },
        "jobCompleted": {
          "type": "integer"
        },
        "lastDeployed": {
          "type": "string"
        },
        "monitored": {
          "type": "boolean"
        },
        "platformType": {
          "type": "string",
          "enum": [
            "vsphere",
            "kvm",
            "hyper-v"
          ]
        },
        "policyName": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "idle",
            "normal",
            "busy",
            "unknown"
          ]
        },
        "totalCPU": {
          "type": "number"
        },
        "totalJobs": {
          "type": "integer"
        },
        "totalRAM": {
          "type": "number"
        },
        "totalVMs": {
          "type": "integer"
        }
      }
    },
    "ResourceListItem": {
      "type": "object",
      "properties": {
        "CPUPercent": {
          "type": "number"
        },
        "RAMPercent": {
          "type": "number"
        },
        "currentCPU": {
          "type": "number"
        },
        "currentRAM": {
          "type": "number"
        },
        "datacenter": {
          "type": "string"
        },
        "dateAdded": {
          "type": "string"
        },
        "hostName": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "isActive": {
          "type": "boolean"
        },
        "jobCompleted": {
          "type": "integer"
        },
        "monitored": {
          "type": "boolean"
        },
        "platformType": {
          "type": "string",
          "enum": [
            "vsphere",
            "kvm",
            "hyper-v"
          ]
        },
        "policyName": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "idle",
            "normal",
            "busy",
            "unknown"
          ]
        },
        "totalCPU": {
          "type": "number"
        },
        "totalJobs": {
          "type": "integer"
        },
        "totalRAM": {
          "type": "number"
        }
      }
    },
    "ResourceVMInfoItem": {
      "type": "object",
      "properties": {
        "CPUPercent": {
          "type": "number"
        },
        "RAMPercent": {
          "type": "number"
        },
        "boincTime": {
          "type": "string"
        },
        "currentCPU": {
          "type": "number"
        },
        "currentRAM": {
          "type": "number"
        },
        "dateCreated": {
          "type": "string"
        },
        "dateDestroyed": {
          "type": "string"
        },
        "guestOS": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "ipAddress": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "poweredOn": {
          "type": "boolean"
        },
        "totalCPU": {
          "type": "number"
        },
        "totalRAM": {
          "type": "number"
        }
      }
    },
    "ResultsItems0": {
      "type": "object",
      "properties": {
        "compatibility": {
          "type": "string"
        },
        "dateAdded": {
          "type": "string",
          "format": "date-time"
        },
        "guestOS": {
          "type": "string"
        },
        "memorySize": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "provisionedSpace": {
          "type": "number"
        },
        "templateType": {
          "type": "string",
          "enum": [
            "datastore",
            "upload"
          ]
        }
      }
    },
    "UserDetailsOKBodyResults": {
      "type": "object",
      "properties": {
        "city": {
          "type": "string"
        },
        "companyName": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "position": {
          "type": "string"
        }
      }
    },
    "UserLoginOKBodyUserInfo": {
      "type": "object",
      "properties": {
        "priority": {
          "type": "string",
          "enum": [
            "Low",
            "Medium",
            "High"
          ]
        },
        "username": {
          "type": "string"
        }
      }
    }
  }
}`))
}
