// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPolicyOKCode is the HTTP code returned for type GetPolicyOK
const GetPolicyOKCode int = 200

/*GetPolicyOK success

swagger:response getPolicyOK
*/
type GetPolicyOK struct {

	/*
	  In: Body
	*/
	Payload *GetPolicyOKBody `json:"body,omitempty"`
}

// NewGetPolicyOK creates GetPolicyOK with default headers values
func NewGetPolicyOK() *GetPolicyOK {

	return &GetPolicyOK{}
}

// WithPayload adds the payload to the get policy o k response
func (o *GetPolicyOK) WithPayload(payload *GetPolicyOKBody) *GetPolicyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get policy o k response
func (o *GetPolicyOK) SetPayload(payload *GetPolicyOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPolicyUnauthorizedCode is the HTTP code returned for type GetPolicyUnauthorized
const GetPolicyUnauthorizedCode int = 401

/*GetPolicyUnauthorized Unauthorized

swagger:response getPolicyUnauthorized
*/
type GetPolicyUnauthorized struct {
}

// NewGetPolicyUnauthorized creates GetPolicyUnauthorized with default headers values
func NewGetPolicyUnauthorized() *GetPolicyUnauthorized {

	return &GetPolicyUnauthorized{}
}

// WriteResponse to the client
func (o *GetPolicyUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetPolicyNotFoundCode is the HTTP code returned for type GetPolicyNotFound
const GetPolicyNotFoundCode int = 404

/*GetPolicyNotFound resource not found

swagger:response getPolicyNotFound
*/
type GetPolicyNotFound struct {

	/*
	  In: Body
	*/
	Payload *GetPolicyNotFoundBody `json:"body,omitempty"`
}

// NewGetPolicyNotFound creates GetPolicyNotFound with default headers values
func NewGetPolicyNotFound() *GetPolicyNotFound {

	return &GetPolicyNotFound{}
}

// WithPayload adds the payload to the get policy not found response
func (o *GetPolicyNotFound) WithPayload(payload *GetPolicyNotFoundBody) *GetPolicyNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get policy not found response
func (o *GetPolicyNotFound) SetPayload(payload *GetPolicyNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPolicyNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
