# Generated by Django 2.2.7 on 2019-12-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('host_address', models.TextField()),
                ('host_name', models.TextField(unique=True)),
                ('total_ram', models.FloatField(blank=True, null=True)),
                ('total_cpu', models.FloatField(blank=True, null=True)),
                ('ram_percent', models.FloatField(blank=True, null=True)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
