# Generated by Django 2.2.7 on 2019-12-08 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.TextField(unique=True)),
                ('vm_name', models.TextField(blank=True, null=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('mem_usage', models.FloatField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('boinc_time', models.DateTimeField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='HostUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('host_address', models.TextField()),
                ('host_name', models.TextField(unique=True)),
                ('total_ram', models.FloatField(blank=True, null=True)),
                ('total_cpu', models.FloatField(blank=True, null=True)),
                ('ram_percent', models.FloatField(blank=True, null=True)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.Resource')),
            ],
        ),
    ]
