# Generated by Django 2.2.7 on 2019-12-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.TextField(unique=True)),
                ('vm_name', models.TextField(blank=True, null=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('mem_usage', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
