# Generated by Django 2.2.7 on 2019-12-01 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_auto_20191201_1336'),
        ('usage', '0002_vmusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostusage',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.Resource'),
        ),
        migrations.AddField(
            model_name='vmusage',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.Resource'),
        ),
    ]
