# Generated by Django 2.2.7 on 2019-12-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0003_auto_20191201_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmusage',
            name='boinc_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmusage',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
