// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteTemplateOKCode is the HTTP code returned for type DeleteTemplateOK
const DeleteTemplateOKCode int = 200

/*DeleteTemplateOK OK

swagger:response deleteTemplateOK
*/
type DeleteTemplateOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteTemplateOKBody `json:"body,omitempty"`
}

// NewDeleteTemplateOK creates DeleteTemplateOK with default headers values
func NewDeleteTemplateOK() *DeleteTemplateOK {

	return &DeleteTemplateOK{}
}

// WithPayload adds the payload to the delete template o k response
func (o *DeleteTemplateOK) WithPayload(payload *DeleteTemplateOKBody) *DeleteTemplateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete template o k response
func (o *DeleteTemplateOK) SetPayload(payload *DeleteTemplateOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTemplateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteTemplateBadRequestCode is the HTTP code returned for type DeleteTemplateBadRequest
const DeleteTemplateBadRequestCode int = 400

/*DeleteTemplateBadRequest bad request

swagger:response deleteTemplateBadRequest
*/
type DeleteTemplateBadRequest struct {
}

// NewDeleteTemplateBadRequest creates DeleteTemplateBadRequest with default headers values
func NewDeleteTemplateBadRequest() *DeleteTemplateBadRequest {

	return &DeleteTemplateBadRequest{}
}

// WriteResponse to the client
func (o *DeleteTemplateBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteTemplateUnauthorizedCode is the HTTP code returned for type DeleteTemplateUnauthorized
const DeleteTemplateUnauthorizedCode int = 401

/*DeleteTemplateUnauthorized Unauthorized

swagger:response deleteTemplateUnauthorized
*/
type DeleteTemplateUnauthorized struct {
}

// NewDeleteTemplateUnauthorized creates DeleteTemplateUnauthorized with default headers values
func NewDeleteTemplateUnauthorized() *DeleteTemplateUnauthorized {

	return &DeleteTemplateUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteTemplateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteTemplateForbiddenCode is the HTTP code returned for type DeleteTemplateForbidden
const DeleteTemplateForbiddenCode int = 403

/*DeleteTemplateForbidden Forbidden

swagger:response deleteTemplateForbidden
*/
type DeleteTemplateForbidden struct {
}

// NewDeleteTemplateForbidden creates DeleteTemplateForbidden with default headers values
func NewDeleteTemplateForbidden() *DeleteTemplateForbidden {

	return &DeleteTemplateForbidden{}
}

// WriteResponse to the client
func (o *DeleteTemplateForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DeleteTemplateNotFoundCode is the HTTP code returned for type DeleteTemplateNotFound
const DeleteTemplateNotFoundCode int = 404

/*DeleteTemplateNotFound resource not found

swagger:response deleteTemplateNotFound
*/
type DeleteTemplateNotFound struct {
}

// NewDeleteTemplateNotFound creates DeleteTemplateNotFound with default headers values
func NewDeleteTemplateNotFound() *DeleteTemplateNotFound {

	return &DeleteTemplateNotFound{}
}

// WriteResponse to the client
func (o *DeleteTemplateNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
