# Generated by Django 2.1 on 2019-11-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191128_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='users',
            new_name='user',
        ),
    ]
