// Code generated by go-swagger; DO NOT EDIT.

package vendor_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteVendorOKCode is the HTTP code returned for type DeleteVendorOK
const DeleteVendorOKCode int = 200

/*DeleteVendorOK deletion success

swagger:response deleteVendorOK
*/
type DeleteVendorOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteVendorOKBody `json:"body,omitempty"`
}

// NewDeleteVendorOK creates DeleteVendorOK with default headers values
func NewDeleteVendorOK() *DeleteVendorOK {

	return &DeleteVendorOK{}
}

// WithPayload adds the payload to the delete vendor o k response
func (o *DeleteVendorOK) WithPayload(payload *DeleteVendorOKBody) *DeleteVendorOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete vendor o k response
func (o *DeleteVendorOK) SetPayload(payload *DeleteVendorOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteVendorOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteVendorUnauthorizedCode is the HTTP code returned for type DeleteVendorUnauthorized
const DeleteVendorUnauthorizedCode int = 401

/*DeleteVendorUnauthorized Unauthorized

swagger:response deleteVendorUnauthorized
*/
type DeleteVendorUnauthorized struct {
}

// NewDeleteVendorUnauthorized creates DeleteVendorUnauthorized with default headers values
func NewDeleteVendorUnauthorized() *DeleteVendorUnauthorized {

	return &DeleteVendorUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteVendorUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteVendorForbiddenCode is the HTTP code returned for type DeleteVendorForbidden
const DeleteVendorForbiddenCode int = 403

/*DeleteVendorForbidden Forbidden

swagger:response deleteVendorForbidden
*/
type DeleteVendorForbidden struct {
}

// NewDeleteVendorForbidden creates DeleteVendorForbidden with default headers values
func NewDeleteVendorForbidden() *DeleteVendorForbidden {

	return &DeleteVendorForbidden{}
}

// WriteResponse to the client
func (o *DeleteVendorForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DeleteVendorNotFoundCode is the HTTP code returned for type DeleteVendorNotFound
const DeleteVendorNotFoundCode int = 404

/*DeleteVendorNotFound resource not found

swagger:response deleteVendorNotFound
*/
type DeleteVendorNotFound struct {

	/*
	  In: Body
	*/
	Payload *DeleteVendorNotFoundBody `json:"body,omitempty"`
}

// NewDeleteVendorNotFound creates DeleteVendorNotFound with default headers values
func NewDeleteVendorNotFound() *DeleteVendorNotFound {

	return &DeleteVendorNotFound{}
}

// WithPayload adds the payload to the delete vendor not found response
func (o *DeleteVendorNotFound) WithPayload(payload *DeleteVendorNotFoundBody) *DeleteVendorNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete vendor not found response
func (o *DeleteVendorNotFound) SetPayload(payload *DeleteVendorNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteVendorNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
