apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtides-backend-deploy
  namespace: default
spec:
  selector:
    matchLabels:
      app: cloudtides-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudtides-backend
    spec:
      containers:
        - name: cloudtides-backend
          image: ericshen97/cloudtides_backend:latest
          ports:
            - containerPort: 80
              hostPort: 8081
          envFrom:
            - secretRef:
                name: cloudtides-secret
      nodeSelector:
        support: backend
