# Generated by Django 2.2.7 on 2019-12-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='password',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
