// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateUserProfileOKCode is the HTTP code returned for type UpdateUserProfileOK
const UpdateUserProfileOKCode int = 200

/*UpdateUserProfileOK success

swagger:response updateUserProfileOK
*/
type UpdateUserProfileOK struct {

	/*
	  In: Body
	*/
	Payload *UpdateUserProfileOKBody `json:"body,omitempty"`
}

// NewUpdateUserProfileOK creates UpdateUserProfileOK with default headers values
func NewUpdateUserProfileOK() *UpdateUserProfileOK {

	return &UpdateUserProfileOK{}
}

// WithPayload adds the payload to the update user profile o k response
func (o *UpdateUserProfileOK) WithPayload(payload *UpdateUserProfileOKBody) *UpdateUserProfileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user profile o k response
func (o *UpdateUserProfileOK) SetPayload(payload *UpdateUserProfileOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateUserProfileUnauthorizedCode is the HTTP code returned for type UpdateUserProfileUnauthorized
const UpdateUserProfileUnauthorizedCode int = 401

/*UpdateUserProfileUnauthorized Unauthorized

swagger:response updateUserProfileUnauthorized
*/
type UpdateUserProfileUnauthorized struct {
}

// NewUpdateUserProfileUnauthorized creates UpdateUserProfileUnauthorized with default headers values
func NewUpdateUserProfileUnauthorized() *UpdateUserProfileUnauthorized {

	return &UpdateUserProfileUnauthorized{}
}

// WriteResponse to the client
func (o *UpdateUserProfileUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// UpdateUserProfileNotFoundCode is the HTTP code returned for type UpdateUserProfileNotFound
const UpdateUserProfileNotFoundCode int = 404

/*UpdateUserProfileNotFound resource not found

swagger:response updateUserProfileNotFound
*/
type UpdateUserProfileNotFound struct {

	/*
	  In: Body
	*/
	Payload *UpdateUserProfileNotFoundBody `json:"body,omitempty"`
}

// NewUpdateUserProfileNotFound creates UpdateUserProfileNotFound with default headers values
func NewUpdateUserProfileNotFound() *UpdateUserProfileNotFound {

	return &UpdateUserProfileNotFound{}
}

// WithPayload adds the payload to the update user profile not found response
func (o *UpdateUserProfileNotFound) WithPayload(payload *UpdateUserProfileNotFoundBody) *UpdateUserProfileNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user profile not found response
func (o *UpdateUserProfileNotFound) SetPayload(payload *UpdateUserProfileNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserProfileNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
