// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UserDetailsOKCode is the HTTP code returned for type UserDetailsOK
const UserDetailsOKCode int = 200

/*UserDetailsOK returns user profile

swagger:response userDetailsOK
*/
type UserDetailsOK struct {

	/*
	  In: Body
	*/
	Payload *UserDetailsOKBody `json:"body,omitempty"`
}

// NewUserDetailsOK creates UserDetailsOK with default headers values
func NewUserDetailsOK() *UserDetailsOK {

	return &UserDetailsOK{}
}

// WithPayload adds the payload to the user details o k response
func (o *UserDetailsOK) WithPayload(payload *UserDetailsOKBody) *UserDetailsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user details o k response
func (o *UserDetailsOK) SetPayload(payload *UserDetailsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserDetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UserDetailsUnauthorizedCode is the HTTP code returned for type UserDetailsUnauthorized
const UserDetailsUnauthorizedCode int = 401

/*UserDetailsUnauthorized Unauthorized

swagger:response userDetailsUnauthorized
*/
type UserDetailsUnauthorized struct {
}

// NewUserDetailsUnauthorized creates UserDetailsUnauthorized with default headers values
func NewUserDetailsUnauthorized() *UserDetailsUnauthorized {

	return &UserDetailsUnauthorized{}
}

// WriteResponse to the client
func (o *UserDetailsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// UserDetailsNotFoundCode is the HTTP code returned for type UserDetailsNotFound
const UserDetailsNotFoundCode int = 404

/*UserDetailsNotFound resource not found

swagger:response userDetailsNotFound
*/
type UserDetailsNotFound struct {

	/*
	  In: Body
	*/
	Payload *UserDetailsNotFoundBody `json:"body,omitempty"`
}

// NewUserDetailsNotFound creates UserDetailsNotFound with default headers values
func NewUserDetailsNotFound() *UserDetailsNotFound {

	return &UserDetailsNotFound{}
}

// WithPayload adds the payload to the user details not found response
func (o *UserDetailsNotFound) WithPayload(payload *UserDetailsNotFoundBody) *UserDetailsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user details not found response
func (o *UserDetailsNotFound) SetPayload(payload *UserDetailsNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserDetailsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
