export default {
    CHANGE: "CHANGE",
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
    ADD_RESOURCE: "ADD_RESOURCE",
    GET_RESOURCES: "GET_RESOURCES",
    GET_RESOURCES_RESPONSE: "GET_RESOURCES_RESPONSE",
    ADD_TEMPLATE: "ADD_TEMPLATE",
    GET_TEMPLATES: "GET_TEMPLATES",
    GET_TEMPLATES_RESPONSE: "GET_TEMPLATES_RESPONSE",
};
