// Code generated by go-swagger; DO NOT EDIT.

package vapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ListVappsOKCode is the HTTP code returned for type ListVappsOK
const ListVappsOKCode int = 200

/*ListVappsOK OK

swagger:response listVappsOK
*/
type ListVappsOK struct {

	/*
	  In: Body
	*/
	Payload []*ListVappsOKBodyItems0 `json:"body,omitempty"`
}

// NewListVappsOK creates ListVappsOK with default headers values
func NewListVappsOK() *ListVappsOK {

	return &ListVappsOK{}
}

// WithPayload adds the payload to the list vapps o k response
func (o *ListVappsOK) WithPayload(payload []*ListVappsOKBodyItems0) *ListVappsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list vapps o k response
func (o *ListVappsOK) SetPayload(payload []*ListVappsOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListVappsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*ListVappsOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListVappsUnauthorizedCode is the HTTP code returned for type ListVappsUnauthorized
const ListVappsUnauthorizedCode int = 401

/*ListVappsUnauthorized Unauthorized

swagger:response listVappsUnauthorized
*/
type ListVappsUnauthorized struct {
}

// NewListVappsUnauthorized creates ListVappsUnauthorized with default headers values
func NewListVappsUnauthorized() *ListVappsUnauthorized {

	return &ListVappsUnauthorized{}
}

// WriteResponse to the client
func (o *ListVappsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
