// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteProjectOKCode is the HTTP code returned for type DeleteProjectOK
const DeleteProjectOKCode int = 200

/*DeleteProjectOK OK

swagger:response deleteProjectOK
*/
type DeleteProjectOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteProjectOKBody `json:"body,omitempty"`
}

// NewDeleteProjectOK creates DeleteProjectOK with default headers values
func NewDeleteProjectOK() *DeleteProjectOK {

	return &DeleteProjectOK{}
}

// WithPayload adds the payload to the delete project o k response
func (o *DeleteProjectOK) WithPayload(payload *DeleteProjectOKBody) *DeleteProjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete project o k response
func (o *DeleteProjectOK) SetPayload(payload *DeleteProjectOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteProjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteProjectBadRequestCode is the HTTP code returned for type DeleteProjectBadRequest
const DeleteProjectBadRequestCode int = 400

/*DeleteProjectBadRequest bad request

swagger:response deleteProjectBadRequest
*/
type DeleteProjectBadRequest struct {
}

// NewDeleteProjectBadRequest creates DeleteProjectBadRequest with default headers values
func NewDeleteProjectBadRequest() *DeleteProjectBadRequest {

	return &DeleteProjectBadRequest{}
}

// WriteResponse to the client
func (o *DeleteProjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteProjectUnauthorizedCode is the HTTP code returned for type DeleteProjectUnauthorized
const DeleteProjectUnauthorizedCode int = 401

/*DeleteProjectUnauthorized Unauthorized

swagger:response deleteProjectUnauthorized
*/
type DeleteProjectUnauthorized struct {
}

// NewDeleteProjectUnauthorized creates DeleteProjectUnauthorized with default headers values
func NewDeleteProjectUnauthorized() *DeleteProjectUnauthorized {

	return &DeleteProjectUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteProjectUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteProjectNotFoundCode is the HTTP code returned for type DeleteProjectNotFound
const DeleteProjectNotFoundCode int = 404

/*DeleteProjectNotFound resource not found

swagger:response deleteProjectNotFound
*/
type DeleteProjectNotFound struct {
}

// NewDeleteProjectNotFound creates DeleteProjectNotFound with default headers values
func NewDeleteProjectNotFound() *DeleteProjectNotFound {

	return &DeleteProjectNotFound{}
}

// WriteResponse to the client
func (o *DeleteProjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
