// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateProjectOKCode is the HTTP code returned for type UpdateProjectOK
const UpdateProjectOKCode int = 200

/*UpdateProjectOK OK

swagger:response updateProjectOK
*/
type UpdateProjectOK struct {

	/*
	  In: Body
	*/
	Payload *UpdateProjectOKBody `json:"body,omitempty"`
}

// NewUpdateProjectOK creates UpdateProjectOK with default headers values
func NewUpdateProjectOK() *UpdateProjectOK {

	return &UpdateProjectOK{}
}

// WithPayload adds the payload to the update project o k response
func (o *UpdateProjectOK) WithPayload(payload *UpdateProjectOKBody) *UpdateProjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update project o k response
func (o *UpdateProjectOK) SetPayload(payload *UpdateProjectOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateProjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateProjectBadRequestCode is the HTTP code returned for type UpdateProjectBadRequest
const UpdateProjectBadRequestCode int = 400

/*UpdateProjectBadRequest bad request

swagger:response updateProjectBadRequest
*/
type UpdateProjectBadRequest struct {
}

// NewUpdateProjectBadRequest creates UpdateProjectBadRequest with default headers values
func NewUpdateProjectBadRequest() *UpdateProjectBadRequest {

	return &UpdateProjectBadRequest{}
}

// WriteResponse to the client
func (o *UpdateProjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateProjectUnauthorizedCode is the HTTP code returned for type UpdateProjectUnauthorized
const UpdateProjectUnauthorizedCode int = 401

/*UpdateProjectUnauthorized Unauthorized

swagger:response updateProjectUnauthorized
*/
type UpdateProjectUnauthorized struct {
}

// NewUpdateProjectUnauthorized creates UpdateProjectUnauthorized with default headers values
func NewUpdateProjectUnauthorized() *UpdateProjectUnauthorized {

	return &UpdateProjectUnauthorized{}
}

// WriteResponse to the client
func (o *UpdateProjectUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// UpdateProjectNotFoundCode is the HTTP code returned for type UpdateProjectNotFound
const UpdateProjectNotFoundCode int = 404

/*UpdateProjectNotFound resource not found

swagger:response updateProjectNotFound
*/
type UpdateProjectNotFound struct {
}

// NewUpdateProjectNotFound creates UpdateProjectNotFound with default headers values
func NewUpdateProjectNotFound() *UpdateProjectNotFound {

	return &UpdateProjectNotFound{}
}

// WriteResponse to the client
func (o *UpdateProjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
