# Generated by Django 2.2.7 on 2019-12-04 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('host_address', models.TextField()),
                ('host_name', models.TextField()),
                ('platform_type', models.CharField(choices=[('1', 'vsphere'), ('2', 'kvm'), ('3', 'hyper-v')], default='vsphere', max_length=10)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('1', 'idle'), ('2', 'busy'), ('3', 'contributing')], default='busy', max_length=20)),
                ('total_disk', models.FloatField(blank=True, null=True)),
                ('total_ram', models.FloatField(blank=True, null=True)),
                ('total_cpu', models.FloatField(blank=True, null=True)),
                ('current_disk', models.FloatField(blank=True, null=True)),
                ('current_ram', models.FloatField(blank=True, null=True)),
                ('current_cpu', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('total_jobs', models.IntegerField(blank=True, default=0, null=True)),
                ('job_completed', models.IntegerField(blank=True, default=0, null=True)),
                ('polling_interval', models.IntegerField(blank=True, null=True)),
                ('monitored', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tides Resource',
                'verbose_name_plural': 'Tides Resources',
            },
        ),
    ]
