# Generated by Django 2.2.7 on 2019-12-01 01:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='host_name',
            field=models.TextField(default=datetime.datetime(2019, 12, 1, 1, 36, 57, 490774, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='host_usage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usage.HostUsage'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='host_address',
            field=models.TextField(),
        ),
    ]
