# Generated by Django 2.2.7 on 2019-12-01 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_vmusage'),
        ('resource', '0002_auto_20191201_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='vm_usage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usage.VMUsage'),
        ),
    ]
