# Generated by Django 2.2.7 on 2019-12-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_resource_vm_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='host_usage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usage.HostUsage'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='vm_usage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usage.VMUsage'),
        ),
    ]
