# Generated by Django 2.2.7 on 2019-12-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_auto_20191201_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='host_usage',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='vm_usage',
        ),
    ]
