apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtides-frontend-deploy
  namespace: default
spec:
  selector:
    matchLabels:
      app: cloudtides-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudtides-frontend
    spec:
      containers:
        - name: cloudtides-frontend
          image: ericshen97/cloudtides_frontend:latest
          ports:
            - containerPort: 80
              hostPort: 80
      nodeSelector:
        support: frontend
